name: BlockyHelp
main: com.blockycraft.blockyhelp.BlockyHelp
version: 1.0.0
author: Bernardo Zukerman
description: Plugin de ajuda para comandos personalizados com páginas automáticas.
commands:
  ajuda:
    description: Exibe uma lista de comandos e suas informações
    usage: /ajuda
    aliases: [help]
permissions:
  blockyhelp.use:
    description: Permite utilizar o comando /ajuda
    default: true
softdepend:
  - BlockyClaim
  - BlockyFactions